name: End-to-end tests
on:
  pull_request:
    branches:
      - "master"
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        
      - name: Report status
        if: success()
        run: npx github-status-reporter success --token ${{ secrets.GITHUB_TOKEN }}
      - name: Report status
        if: failure()
        run: npx github-status-reporter failure --token ${{ secrets.GITHUB_TOKEN }}
